name: Update live data

permissions:
  contents: write

on:
  schedule:
    # Run every 15 minutes at 2, 17, 32, and 47 minutes past the hour (UTC)
    # According to the LCRA (https://hydromet.lcra.org/media),
    # the water data is gathered every 15 minutes and then it takes
    # about 2 minutes to generate new reports.
    - cron: "2,17,32,47 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  refresh-live-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Generate live fullness snapshot
        run: |
          node .github/workflows/compute-live-fullness.js
