name: Update data

permissions:
  contents: write

on:
  schedule:
    # Run every hour at 30 minutes past the hour (UTC)
    - cron: "30 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove stale data
        run: rm assets/data/travis.csv assets/data/travis-10year.csv

      - name: Fetch latest data
        run: |
          curl -o assets/data/travis.csv https://waterdatafortexas.org/reservoirs/individual/travis.csv

      - name: Verify file was downloaded
        run: |
          if [ -f assets/data/travis.csv ]; then
            echo "File downloaded successfully"
            echo "File size: $(wc -c < assets/data/travis.csv) bytes"
            echo "First few lines:"
            head -5 assets/data/travis.csv
          else
            echo "Error: File was not downloaded"
            exit 1
          fi

      - name: Extract last 10 years of data (3650 lines)
        run: |
          # Extract the header (first non-comment line)
          awk '!/^#/' assets/data/travis.csv | head -n 1 > assets/data/travis-10year.csv
          # Append the last 3650 data lines
          tail -n 3650 assets/data/travis.csv >> assets/data/travis-10year.csv

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/data/travis.csv assets/data/travis-10year.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Lake Travis water level data - $(date)"
            git push
          fi
